// employee types
export const GET_EMPLOYEES = 'GET_EMPLOYEES'
export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BYid'
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const UPDATE_EMPLOYEE_BY_ID = 'UPDATE_EMPLOYEE_BYid'
export const DELETE_EMPLOYEE_BY_ID = 'DELETE_EMPLOYEE_BYid'


// cafe types
export const GET_CAFES = 'GET_CAFES'
export const GET_CAFE_BY_ID = 'GET_CAFE_BYid'
export const CREATE_CAFE = 'CREATE_CAFE'
export const UPDATE_CAFE_BY_ID = 'UPDATE_CAFE_BYid'
export const DELETE_CAFE_BY_ID = 'DELETE_CAFE_BYid'
export const GET_CAFE_BY_LOCATION = 'GET_CAFE_BY_LOCATION'
export const GET_EMPLOYEES_BY_CAFE = 'GET_EMPLOYEES_BY_CAFE'